# Generated by Django 5.2.7 on 2026-01-09 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shiprocket_issue_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='shiprocket_issue_reason',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
