# Generated by Django 5.2.7 on 2025-11-25 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftset',
            name='original_price',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='original_price',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
