# Generated by Django 5.2.7 on 2025-12-23 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_panel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='helpquery',
            name='admin_reply',
        ),
        migrations.AlterField(
            model_name='helpquery',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='helpquery',
            name='subject',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
