# Generated by Django 5.2.7 on 2026-01-08 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_panel', '0002_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='addressmodel',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
